EAPI=9
DESCRIPTION="A utility for generating the cpu flags use expand variables"
LICENSE="public-domain"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

# We need the cpudif2cpuflags tool to generate the use flags, after the install
# we can get rid of the cpuid2cpuflags package.
BDEPEND="app-portage/cpuid2cpuflags"

S="${WORKDIR}"

src_compile() {
	echo "# Automatically generated by ${CATEGORY}/$P" | tee -a 00-cpuflags
	echo "*/* $(cpuid2cpuflags)" | tee -a 00-cpuflags
}

src_install() {
	insinto /etc/portage/package.use/
	doins 00-cpuflags
}

pkg_postinst() {
	elog "The /etc/portage/package.use/00-cpuflags has been created"
}
