#  _   ___   ______  ____  _        _    _   _ ____
# | | | \ \ / /  _ \|  _ \| |      / \  | \ | |  _ \
# | |_| |\ V /| |_) | |_) | |     / _ \ |  \| | | | |
# |  _  | | | |  __/|  _ <| |___ / ___ \| |\  | |_| |
# |_| |_| |_| |_|   |_| \_\_____/_/   \_\_| \_|____/
# __        _____  ____  _  ______  ____   _    ____ _____ ____
# \ \      / / _ \|  _ \| |/ / ___||  _ \ / \  / ___| ____/ ___|
#  \ \ /\ / / | | | |_) | ' /\___ \| |_) / _ \| |   |  _| \___ \
#   \ V  V /| |_| |  _ <| . \ ___) |  __/ ___ \ |___| |___ ___) |
#    \_/\_/  \___/|_| \_\_|\_\____/|_| /_/   \_\____|_____|____/

workspace = 1,  persistent:true
workspace = 2,  persistent:true
workspace = 3,  persistent:true
workspace = 4,  persistent:true
workspace = 5,  persistent:true
workspace = 6,  persistent:true
workspace = 7,  persistent:true
workspace = 8,  persistent:true
workspace = 9,  persistent:true
workspace = 10, persistent:true

# The special workspace will not scroll as the intention is to use this for
# quick access. Hence the expectation is that not many windows will be requred
# so dwingling should satisfy these assumption.
workspace = s[true], layout: dwindle


# Adjust the gaps for a workspace with a single window
workspace  = w[tv1], gapsout:8, gapsin:0
workspace  = f[true], gapsout:8, gapsin:0
