#  ____   ___  ____ _____  _    ____ _____
# |  _ \ / _ \|  _ \_   _|/ \  / ___| ____|
# | |_) | | | | |_) || | / _ \| |  _|  _|
# |  __/| |_| |  _ < | |/ ___ \ |_| | |___
# |_|    \___/|_| \_\|_/_/   \_\____|_____|
#  __  __    _    _  _______   ____ ___  _   _ _____
# |  \/  |  / \  | |/ / ____| / ___/ _ \| \ | |  ___|
# | |\/| | / _ \ | ' /|  _|  | |  | | | |  \| | |_
# | |  | |/ ___ \| . \| |___ | |__| |_| | |\  |  _|
# |_|  |_/_/   \_\_|\_\_____(_)____\___/|_| \_|_|
#
# This is the main configuration file for portage. Edit this file to configure
# portage for your specific system. The configuration is also split across
# multiple files which may be updated. But this file is the global
# configurations for the system.
#
# The official documentation is available via the man pages; or the Gentoo
# wiki, which goes into greater detail on configuring portage.
#
# Wiki:   https://wiki.gentoo.org/wiki//etc/portage/make.conf
# Manual: man 5 make.conf

EMERGE_DEFAULT_OPTS="--ask --quiet --verbose --jobs=1 --load=1"
FEATURES="candy parallel-fetch parallel-install"
PORTAGE_NICENESS=2
PORTAGE_COMPRESS="zstd"
BINPKG_COMPRESS="zstd"

# PORTAGE DIRECTORIES
#
# These are the directories used by portage, and should probably not be
# changed.
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
PORTAGE_TMPDIR="/var/tmp"

# BUILD FLAGS
#
# Generally -O2 is the recommended level of optimisation; however, packages can
# be compiled with -march=native or -C target-cpu=native (for Rust) to build
# for the specific cpu the system is running on.
#
# Changing the build flags may require a system-wide package re-build as these
# are global. Further overrides may be done on package an individual package
# basis in the portage/package.env file.
#
# Please see the Gentoo wiki for official documentation and recommendations.
#
# Consider setting the MAKEOPTS according to the number of threads available on
# the system (output of nproc). A safe default value is probably 2.
COMMON_FLAGS="-O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C opt-level=3"
MAKEOPTS="-j2 -l2"

LC_MESSAGES=C.utf8
GRUB_PLATFORMS="efi-64"
GENTOO_MIRRORS="https://mirror.bytemark.co.uk/gentoo/ \
    https://www.irrorservice.org/sites/distfiles.gentoo.org/"
